import type {
  Task,
  Project,
  Goal,
  Habit,
  CalendarEvent,
  ChatMessage,
  Note,
  AIRecommendation,
  EnergyPoint,
  AnalyticsPoint,
} from './types';

export const tasks: Task[] = [
  {
    id: 't1',
    title: 'Finalize Q3 product strategy doc',
    description: 'Synthesize feedback from leadership review and lock the roadmap.',
    status: 'in_progress',
    priority: 'urgent',
    energy: 'high',
    estimatedMinutes: 90,
    actualMinutes: 35,
    dueAt: '2026-07-26T17:00:00Z',
    scheduledAt: '2026-07-26T09:00:00Z',
    tags: ['strategy', 'leadership'],
    projectId: 'p1',
    subtasks: [
      { id: 's1', title: 'Collect leadership comments', done: true },
      { id: 's2', title: 'Rewrite roadmap section', done: false },
      { id: 's3', title: 'Send for final approval', done: false },
    ],
    dependencies: [],
    createdAt: '2026-07-22T10:00:00Z',
  },
  {
    id: 't2',
    title: 'Review pull requests for auth refactor',
    status: 'todo',
    priority: 'high',
    energy: 'medium',
    estimatedMinutes: 45,
    dueAt: '2026-07-26T20:00:00Z',
    tags: ['engineering'],
    projectId: 'p2',
    subtasks: [],
    dependencies: [],
    createdAt: '2026-07-25T08:00:00Z',
  },
  {
    id: 't3',
    title: 'Draft investor update email',
    status: 'todo',
    priority: 'high',
    energy: 'medium',
    estimatedMinutes: 30,
    scheduledAt: '2026-07-26T14:00:00Z',
    tags: ['fundraising'],
    subtasks: [],
    dependencies: [],
    createdAt: '2026-07-25T12:00:00Z',
  },
  {
    id: 't4',
    title: 'Morning workout — strength',
    status: 'done',
    priority: 'medium',
    energy: 'high',
    estimatedMinutes: 50,
    actualMinutes: 52,
    tags: ['health'],
    subtasks: [],
    dependencies: [],
    createdAt: '2026-07-26T06:00:00Z',
  },
  {
    id: 't5',
    title: 'Read chapter 4 — Deep Work',
    status: 'todo',
    priority: 'low',
    energy: 'low',
    estimatedMinutes: 25,
    tags: ['learning'],
    subtasks: [],
    dependencies: [],
    createdAt: '2026-07-24T19:00:00Z',
  },
  {
    id: 't6',
    title: 'Prepare slides for design review',
    status: 'todo',
    priority: 'urgent',
    energy: 'high',
    estimatedMinutes: 60,
    dueAt: '2026-07-27T10:00:00Z',
    tags: ['design'],
    projectId: 'p1',
    subtasks: [
      { id: 's4', title: 'Outline narrative', done: true },
      { id: 's5', title: 'Build visuals', done: false },
    ],
    dependencies: ['t1'],
    createdAt: '2026-07-25T15:00:00Z',
  },
  {
    id: 't7',
    title: 'Reply to partnership inquiry',
    status: 'todo',
    priority: 'medium',
    energy: 'low',
    estimatedMinutes: 15,
    tags: ['email'],
    subtasks: [],
    dependencies: [],
    createdAt: '2026-07-26T07:00:00Z',
  },
];

export const projects: Project[] = [
  {
    id: 'p1',
    name: 'Product Strategy',
    description: 'Define and communicate the Q3-Q4 product direction.',
    color: 'hsl(199 89% 60%)',
    progress: 68,
    taskCount: 8,
    dueAt: '2026-08-15T00:00:00Z',
  },
  {
    id: 'p2',
    name: 'Auth Refactor',
    description: 'Migrate authentication to a unified identity layer.',
    color: 'hsl(152 62% 48%)',
    progress: 42,
    taskCount: 14,
    dueAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'p3',
    name: 'Brand Refresh',
    description: 'New visual identity and marketing site.',
    color: 'hsl(280 70% 65%)',
    progress: 85,
    taskCount: 6,
    dueAt: '2026-08-05T00:00:00Z',
  },
  {
    id: 'p4',
    name: 'Personal — Marathon Training',
    description: '18-week training plan for the autumn marathon.',
    color: 'hsl(38 92% 55%)',
    progress: 30,
    taskCount: 5,
  },
];

export const goals: Goal[] = [
  {
    id: 'g1',
    title: 'Ship Nova AI public beta',
    category: 'Product',
    progress: 64,
    targetDate: '2026-10-01',
    status: 'on_track',
    milestones: [
      { id: 'm1', title: 'Closed alpha', done: true, date: '2026-07-01' },
      { id: 'm2', title: 'Onboarding flow', done: true, date: '2026-07-20' },
      { id: 'm3', title: 'AI memory v2', done: false, date: '2026-08-15' },
      { id: 'm4', title: 'Public launch', done: false, date: '2026-10-01' },
    ],
  },
  {
    id: 'g2',
    title: 'Run a sub-4 marathon',
    category: 'Health',
    progress: 35,
    targetDate: '2026-11-10',
    status: 'on_track',
    milestones: [
      { id: 'm5', title: 'Half marathon under 1:55', done: true, date: '2026-07-10' },
      { id: 'm6', title: '30km long run', done: false, date: '2026-09-01' },
      { id: 'm7', title: 'Race day', done: false, date: '2026-11-10' },
    ],
  },
  {
    id: 'g3',
    title: 'Reach $25K MRR',
    category: 'Business',
    progress: 22,
    targetDate: '2026-12-31',
    status: 'at_risk',
    milestones: [
      { id: 'm8', title: 'First 10 paying customers', done: true, date: '2026-06-15' },
      { id: 'm9', title: '100 customers', done: false, date: '2026-09-15' },
      { id: 'm10', title: '$25K MRR', done: false, date: '2026-12-31' },
    ],
  },
  {
    id: 'g4',
    title: 'Read 24 books this year',
    category: 'Learning',
    progress: 50,
    targetDate: '2026-12-31',
    status: 'on_track',
    milestones: [
      { id: 'm11', title: '12 books by midyear', done: true, date: '2026-06-30' },
      { id: 'm12', title: '24 books', done: false, date: '2026-12-31' },
    ],
  },
];

export const habits: Habit[] = [
  {
    id: 'h1',
    name: 'Deep work session',
    icon: 'Brain',
    streak: 14,
    bestStreak: 23,
    completedToday: true,
    weeklyRate: 0.86,
    history: [true, true, true, false, true, true, true],
  },
  {
    id: 'h2',
    name: 'Morning run',
    icon: 'Footprints',
    streak: 6,
    bestStreak: 41,
    completedToday: true,
    weeklyRate: 0.71,
    history: [true, false, true, true, true, true, true],
  },
  {
    id: 'h3',
    name: 'Read 20 minutes',
    icon: 'BookOpen',
    streak: 9,
    bestStreak: 15,
    completedToday: false,
    weeklyRate: 0.64,
    history: [true, true, false, true, true, true, false],
  },
  {
    id: 'h4',
    name: 'No phone before noon',
    icon: 'Smartphone',
    streak: 3,
    bestStreak: 12,
    completedToday: true,
    weeklyRate: 0.43,
    history: [false, false, true, true, false, true, true],
  },
  {
    id: 'h5',
    name: 'Journal',
    icon: 'PenLine',
    streak: 21,
    bestStreak: 21,
    completedToday: true,
    weeklyRate: 1.0,
    history: [true, true, true, true, true, true, true],
  },
];

export const todayEvents: CalendarEvent[] = [
  {
    id: 'e1',
    title: 'Deep Work — Strategy doc',
    start: '2026-07-26T09:00:00Z',
    end: '2026-07-26T10:30:00Z',
    type: 'deep_work',
    aiSuggested: true,
  },
  {
    id: 'e2',
    title: 'Standup with engineering',
    start: '2026-07-26T11:00:00Z',
    end: '2026-07-26T11:30:00Z',
    type: 'meeting',
    location: 'Zoom',
  },
  {
    id: 'e3',
    title: 'Lunch + walk',
    start: '2026-07-26T12:30:00Z',
    end: '2026-07-26T13:30:00Z',
    type: 'break',
  },
  {
    id: 'e4',
    title: 'Investor update — draft',
    start: '2026-07-26T14:00:00Z',
    end: '2026-07-26T14:30:00Z',
    type: 'deep_work',
    aiSuggested: true,
  },
  {
    id: 'e5',
    title: 'Design review',
    start: '2026-07-26T15:30:00Z',
    end: '2026-07-26T16:30:00Z',
    type: 'meeting',
    location: 'Studio B',
  },
  {
    id: 'e6',
    title: 'Reading — Deep Work ch.4',
    start: '2026-07-26T20:00:00Z',
    end: '2026-07-26T20:30:00Z',
    type: 'personal',
    aiSuggested: true,
  },
];

export const chatMessages: ChatMessage[] = [
  {
    id: 'c1',
    role: 'assistant',
    content:
      "Good morning. You have 3 high-priority items today and a 90-minute window at 9am that matches your peak energy. I've blocked it for the strategy doc. Want me to move your standup prep to 8:45?",
    createdAt: '2026-07-26T07:00:00Z',
    actions: [
      { type: 'schedule', label: 'Block 9–10:30am for strategy doc', applied: true },
      { type: 'reminder', label: 'Remind me at 8:45 to prep for standup', applied: false },
    ],
  },
  {
    id: 'c2',
    role: 'user',
    content: 'Yes, and also push the investor email to after lunch. I need a clear head for it.',
    createdAt: '2026-07-26T07:02:00Z',
  },
  {
    id: 'c3',
    role: 'assistant',
    content:
      'Done — investor draft is now at 2pm, right after your lunch walk so you return refreshed. I also flagged two PRs that need your eyes before the 4pm design review. Shall I summarize them?',
    createdAt: '2026-07-26T07:02:30Z',
    actions: [
      { type: 'schedule', label: 'Move investor email to 2pm', applied: true },
      { type: 'create_task', label: 'Review 2 PRs before 4pm', applied: true },
    ],
  },
];

export const notes: Note[] = [
  {
    id: 'n1',
    title: 'Product strategy — key themes',
    excerpt: 'Three pillars for Q3: AI memory, onboarding, and trust...',
    body: 'Three pillars for Q3: AI memory, onboarding, and trust. The memory system is the moat — long-term context is what makes Nova feel like a partner rather than a chatbot.',
    tags: ['strategy', 'product'],
    updatedAt: '2026-07-25T18:00:00Z',
    pinned: true,
  },
  {
    id: 'n2',
    title: '1:1 with Maya — notes',
    excerpt: 'Career growth conversation. Maya wants more ownership...',
    body: 'Career growth conversation. Maya wants more ownership of the memory system. Agreed to a 60-day plan with weekly check-ins.',
    tags: ['people', '1on1'],
    updatedAt: '2026-07-24T16:00:00Z',
    pinned: false,
  },
  {
    id: 'n3',
    title: 'Marathon training reflections',
    excerpt: 'Felt strong on the long run. Pace is trending down...',
    body: 'Felt strong on the long run. Pace is trending down but heart rate stayed in zone 2. Need to add one more tempo session per week.',
    tags: ['health', 'running'],
    updatedAt: '2026-07-23T07:00:00Z',
    pinned: false,
  },
  {
    id: 'n4',
    title: 'Book notes — Deep Work',
    excerpt: 'The ability to focus without distraction is increasingly rare...',
    body: 'The ability to focus without distraction is increasingly rare and therefore increasingly valuable. Schedule deep work like a meeting with yourself.',
    tags: ['learning', 'books'],
    updatedAt: '2026-07-22T21:00:00Z',
    pinned: false,
  },
];

export const recommendations: AIRecommendation[] = [
  {
    id: 'r1',
    title: 'Protect your 9–10:30am deep work block',
    rationale:
      'Your energy peaks in the morning and the strategy doc is your highest-leverage task. I declined a tentative meeting invite for 9:15.',
    type: 'focus',
    impact: 'high',
  },
  {
    id: 'r2',
    title: 'Move the investor email to 2pm',
    rationale:
      'You write best after light movement. The post-lunch walk historically boosts your writing output by ~20%.',
    type: 'schedule',
    impact: 'medium',
  },
  {
    id: 'r3',
    title: 'Reschedule "Read ch.4" to 8pm',
    rationale:
      'Low-energy task placed in your evening wind-down window, freeing afternoon focus for the design review.',
    type: 'schedule',
    impact: 'low',
  },
  {
    id: 'r4',
    title: 'Your "No phone before noon" habit is slipping',
    rationale:
      '3 misses this week. Want a charging-station reminder at 10:45pm to set up for tomorrow?',
    type: 'habit',
    impact: 'medium',
  },
];

export const energyCurve: EnergyPoint[] = [
  { hour: 6, value: 30 },
  { hour: 7, value: 45 },
  { hour: 8, value: 65 },
  { hour: 9, value: 92 },
  { hour: 10, value: 95 },
  { hour: 11, value: 78 },
  { hour: 12, value: 55 },
  { hour: 13, value: 48 },
  { hour: 14, value: 72 },
  { hour: 15, value: 80 },
  { hour: 16, value: 70 },
  { hour: 17, value: 60 },
  { hour: 18, value: 50 },
  { hour: 19, value: 40 },
  { hour: 20, value: 35 },
  { hour: 21, value: 30 },
];

export const weeklyAnalytics: AnalyticsPoint[] = [
  { label: 'Mon', focus: 4.5, completion: 80 },
  { label: 'Tue', focus: 5.5, completion: 92 },
  { label: 'Wed', focus: 3.2, completion: 60 },
  { label: 'Thu', focus: 6.0, completion: 95 },
  { label: 'Fri', focus: 4.8, completion: 88 },
  { label: 'Sat', focus: 2.1, completion: 40 },
  { label: 'Sun', focus: 1.5, completion: 30 },
];
